FROM almalinux:10-minimal

ARG user=mysql

ARG data=/var/lib/mysql
ARG run=/var/run/mysql
ARG cfg=/etc/my.cnf.d
ARG lib=/usr/lib64/mysql

# MariaDB 12.2 stable (GA) release
COPY mariadb/mariadb.repo  /etc/yum.repos.d/

# Prepare OS
RUN microdnf update -y && microdnf install -y tzdata shadow-utils

# Add user + application paths + user permissions
RUN useradd --system --no-create-home -U -u 777 -s /sbin/nologin $user && \
    mkdir -p $data $run && chown $user:$user $data $run && chmod 755 $data $run

# Install MariaDB
RUN microdnf install -y MariaDB-server MariaDB-client

# Remove OS tools
RUN microdnf remove -y shadow-utils && \
    microdnf clean all && \
    rm -rf /var/cache/yum

# Copy config files & scripts
COPY mariadb/my.cnf  /etc/
COPY mariadb/mariadb.sh  /opt/

# User permissions
RUN chown $user:$user /etc/my.cnf $cfg $lib && \
    chmod 644 /etc/my.cnf && chmod 755 $cfg $lib && \
    find $cfg $lib -type f -exec chmod 644 {} \; && \
    find $cfg $lib -type d -exec chmod 755 {} \; && \
    chown $user:$user /opt/mariadb.sh && chmod 544 /opt/mariadb.sh


VOLUME ["$data"]

EXPOSE 3306/tcp

USER $user

ENTRYPOINT ["/opt/mariadb.sh"]
