x-common-env: &env
  TZ: "Europe/Zurich"

services:

  frontend:
    environment:
      <<: *env
    #ports:
    #  - "4777:443"

  backend:
    environment:
      <<: *env

  yfinance:
    environment:
      <<: *env

  ai:
    environment:
      <<: *env

  mariadb:
    environment:
      <<: *env
      # MARIADB_DATABASE: "expose"
      # MARIADB_USER: "expose"
      MARIADB_PASSWORD: "change-me"
      MARIADB_ROOT_PASSWORD: "change-me"
    # ports:
    #   - "3307:3306"
    # volumes:
    #   - /path/to/expose/db:/var/lib/mysql:delegated

  temporal-db:
    environment:
      <<: *env
      # MYSQL_DATABASE: "temporal"
      # MYSQL_VISIBILITY_DATABASE: "temporal_visibility"
      # MYSQL_USER: "temporal"
      MYSQL_PASSWORD: "change-me"
      MYSQL_ROOT_PASSWORD: "change-me"
    # ports:
    #   - "3308:3306"
    # volumes:
    #   - /path/to/expose/temporal-db:/var/lib/mysql:delegated


  temporal:
    environment:
      <<: *env
      # MYSQL_USER: "temporal"
      MYSQL_PWD: "change-me"
    # ports:
    #   - "7234:7233"

  temporal-db-schema:
    environment:
      <<: *env
      MYSQL_PWD: "change-me"

  temporal-namespace:
    environment:
      <<: *env
      # DEFAULT_NAMESPACE: "expose"
      # DEFAULT_NAMESPACE_RETENTION: "72h"

  temporal-admin:
    environment:
      <<: *env

  temporal-ui:
    environment:
      <<: *env
      # TEMPORAL_CORS_ORIGINS: "http://localhost:3000"
    # ports:
    #   - "8080:8080"
