name: Continuous Integration (CI)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run dotnet build
        run: dotnet build -c Release -v minimal

      #- name: Run 'dotnet test'
      #  run: dotnet test -c Release -v minimal tests/Expose.Tests
